apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-unseal-controller
  namespace: vault
  labels:
    app.kubernetes.io/name: vault-unseal-controller
    app.kubernetes.io/component: controller
